import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import React from "react";
import Head from 'next/head'
import Header from '@/components/header'
import Footer from '@/components/footer'
import styles from '@/styles/Home.module.css'

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <React.Fragment>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <Header />
                <main className={styles.main}>
                    <Component {...pageProps} />
                </main>
                <Footer />
            </div>

        </React.Fragment>
    )
}

export default MyApp
